flags: {}
packages:
  - '.'
  - extra-dep: true
    location:
      git: https://github.com/isovector/th-dict-discovery.git
      commit: d6c8c77abc87b364b0ac6568d6aec6798a635340
  - extra-dep: true
    location:
      git: https://github.com/isovector/htiled.git
      commit: bb18e7dd85b3f1fe8f9e339f8e6b8ea942bbe361
  - extra-dep: true
    location:
      git: https://github.com/isovector/QuadTree.git
      commit: 4f2993f3ae31d45216b06c6cbc9ea8da3f8bcf09
  - extra-dep: true
    location:
      git: https://github.com/isovector/sequoia.git
      commit: 4f4dd05fbbc311c1a8a2691cda4ee45a9086dbe1
  - extra-dep: true
    location:
      git: https://github.com/isovector/bones.git
      commit: f436c93a56c7b7959f413f1998a4668241371b9a

extra-deps:
  - sdl2-2.1.3
  - frpnow-0.18
  - recursion-schemes-5.0.2


resolver: lts-7.1
