flags: {}
packages:
  - '.'
  - '../ecstasy'
  - '../sequoia'
  - '../bones'
  - extra-dep: true
    location:
      git: https://github.com/chrra/htiled.git
      commit: a0b473676b73bfa172899499c8ba6b0dc6b16a1f
  - extra-dep: true
    location:
      git: https://github.com/schell/aeson-tiled.git
      commit: 32fa27eb3313723062cbc771539c101ad3e5f0af

extra-deps:
  - sdl2-2.3.0
  - frpnow-0.18
  - recursion-schemes-5.0.2
  - astar-0.3.0.0
  - aeson-1.2.2.0
  - th-abstraction-0.2.6.0
  - transformers-0.5.5.0
  - jps-0.1.0.0

resolver: lts-11.9
