flags: {}
packages:
  - '.'
  - extra-dep: true
    location:
      git: https://github.com/isovector/htiled.git
      commit: bb18e7dd85b3f1fe8f9e339f8e6b8ea942bbe361
  - extra-dep: true
    location:
      git: https://github.com/schell/aeson-tiled.git
      commit: 32fa27eb3313723062cbc771539c101ad3e5f0af
  - extra-dep: true
    location:
      git: https://github.com/isovector/QuadTree.git
      commit: 4f2993f3ae31d45216b06c6cbc9ea8da3f8bcf09
  - extra-dep: true
    location:
      git: https://github.com/isovector/sequoia.git
      commit: 605f5124cc31e31a6f7a6ef68f4636d10d267b10

extra-deps:
  - sdl2-2.3.0
  - frpnow-0.18
  - recursion-schemes-5.0.2
  - astar-0.3.0.0
  - aeson-1.2.2.0
  - th-abstraction-0.2.6.0
  - ecstasy-0.1.1.0


resolver: lts-9.0
